version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt
      - pip install pytest
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 493608842247.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Running unit tests...
      - pytest tests || exit 1
      - echo Building the Docker image...
      - docker build -t flask-devops-app .
      - docker tag flask-devops-app:latest 493608842247.dkr.ecr.us-east-1.amazonaws.com/flask-devops-app:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 493608842247.dkr.ecr.us-east-1.amazonaws.com/flask-devops-app:latest

artifacts:
  files: []

